server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  server:
    response-cache-update-interval-ms: 3000
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false #????
#    registry-fetch-interval-seconds: 30
    fetch-registry: false #????
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
